name = "image-transformer"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[services]]
binding = "IMAGE_TRANSFORMER"
service = "image-transformer-container"

[[containers]]
name = "image-transformer-container"
image = "./Dockerfile"

[observability]
enabled = true
