name = "sharp-service"
main = "src/index.js"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "SHARP_SERVICE"
class_name = "SharpService"

[[migrations]]
tag = "v1"
new_classes = ["SharpService"]

[[containers]]
class_name = "SharpService"
image = "./Dockerfile"

[observability]
enabled = true
