name = "image-transformer"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "IMAGE_TRANSFORMER"
class_name = "ImageTransformer"

[[migrations]]
tag = "v1"
new_classes = ["ImageTransformer"]

[[containers]]
class_name = "ImageTransformer"
image = "./Dockerfile"

[observability]
enabled = true
